places = ['paris', 'japan','mexico','thailand','nepal','srilanka']
print(places)
print(sorted(places))
print(places)
print(sorted(places , reverse=True))
print(places)
print(places.reverse())
print(places)
print(places.reverse())
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)